// Test JavaScript project for GitHub deployment
const express = require('express');
const app = express();
const PORT = process.env.PORT || 3000;

app.get('/', (req, res) => {
  res.json({
    message: 'MultiLLM GitHub Integration Test',
    timestamp: new Date().toISOString(),
    platform: 'Generated by MultiLLM AI Platform',
    features: [
      'AI-powered code generation',
      'Real-time GitHub integration', 
      'Automatic deployment',
      'Multi-language support'
    ]
  9});
});

app.get('/health', (req, res) => {
  res.json({ status: 'ok', service: 'multillm-test' });
});

app.listen(PORT, () => {
  console.log(`MultiLLM test server running on port ${PORT}`);
});

// Export for testing
module.exports = app;